### ISSUE TITLE
Question about default `min_heap_size` in `exometer_probe`

### ISSUE THREAD

**Issue by surik** [Feuerlabs/exometer_core#100]
Each `exometer_probe` has set the default [min_heap_size](https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_probe.erl#L644) to 40000. If I understand it correctly it might be the reason for big memory consumption. According to [Erlang documentation](http://erlang.org/doc/efficiency_guide/processes.html):
```
Initial Heap Size
...

The gain is twofold:

* Although the garbage collector grows the heap, it grows it step-by-step, 
  which is more costly than directly establishing a larger heap when the process is spawned.
* The garbage collector can also shrink the heap if it is much larger than 
  the amount of data stored on it; setting the minimum heap size prevents that.
```
I can observe interesting behavior in my test system where I have around 5000 histograms. That they immediately on startup allocate around 1.5Gb data and during the system running the amount of memory is growing and it seems that GC doesn't collect data from `exometer_prob` processes.

As soon I set `min_heap_size` to default value everything works better. Around 200Mb on startup for 5000 histograms and seems that GC cleans them time to time.

Since there is an ability to tune this value via probe options can we use `min_heap_size` with value by default?

Thanks in advance and sorry if it was already discussed somewhere.

**Comment by surik** [comment]
See #102

**Comment by mpope9** [comment]
Is there any chance this will be merged?

**Comment by tolbrino** [comment]
#102 has been merged.
