### ISSUE TITLE
New version for hex.pm?

### ISSUE THREAD

**Issue by surik** [Feuerlabs/exometer_core#112]
Version 1.5.2 was released 12.09.17. I see that master has some changes like using `parse_transform` 3.2.0. 

I would really happy to have new version of `exometer_core`. Then I would be able to release [travelping/exometer_influxdb](https://github.com/travelping/exometer_influxdb) 0.5.9 which wants to use hackney 1.12.1 (which depends on parse_transform 3.2.0).  Currently I'm having problem with publish `exometer_influxdb` to hex.pm because these version mismatches between `hacknhey` and `exometer_core`.

**Comment by surik** [comment]
I think I need to ping @fishcakez and @tsloughter as they are in the list of the owners for https://hex.pm/packages/exometer_core ;)

**Comment by netDalek** [comment]
Anybody here. @fishcakez, @tsloughter. Please help

**Comment by tsloughter** [comment]
Hm, didn't know that :). I suppose I can publish a release then.

But since I don't use exometer it would be nice to find someone who does and wants to take on this responsibility.

@Licenser ok with you if we add someone to the hex maintainers?

**Comment by tsloughter** [comment]
Oi, so someone who wants this on hex should send a PR to replace the git dependencies with hex dependencies.

**Comment by tolbrino** [comment]
@surik I will create a new maintenance release after #116 has been merged.

@tsloughter You can add me to the list of maintainers.

**Comment by tolbrino** [comment]
I created the release `1.5.3`, since there was an inconsistency between the actual tags in the repo and the versions on hex.

**Comment by tsloughter** [comment]
@tolbrino thanks, I've added you.

**Comment by tolbrino** [comment]
@surik @tsloughter I've published version [1.5.4](https://hex.pm/packages/exometer_core/1.5.4). Let me know if there are any issues.
