### ISSUE TITLE
Metrics find and select are not retried when subscribbed to statically

### ISSUE THREAD

**Issue by amiramix** [Feuerlabs/exometer_core#12]
Subscribers declared statically (in the app.config) may want to subscribe to metrics that don't exist until the system is fully booted up. In case of metrics defined as lists (e.g. [atom, atom, atom]) such report are forced to be retried using the RetryFailedMetrics flag. But this flag doesn't apply to metrics defined as 'find' or 'select' (e.g. {find, [atom]}).

Such behaviour is not documented and in my opinion should be considered a bug since if someone is concerned about retrying invalid metrics they should not be setting the RetryFailedMetrics flag to true.

**Comment by uwiger** [comment]
The way to create separate pull requests is to have different branches on your side, and then create one PR from each.

**Comment by amiramix** [comment]
Done. I created a separate pull request for the non-functional changes. I can't create a separate pull request just for the second commit until the first one is integrated (in which case the existing one should start showing only the second commit in it's diff).

**Comment by amiramix** [comment]
I didn't, I had to recreate the pull request.
