### ISSUE TITLE
exometer:re_register causes process leak

### ISSUE THREAD

**Issue by netDalek** [Feuerlabs/exometer_core#120]
Is it ok, that the amount of processes grows up each time I use re_register?

```
1> application:ensure_all_started(exometer_core).
{ok,[]}
2> {exometer:re_register([name], spiral, []), length(erlang:processes())}.
{ok,78}
3> {exometer:re_register([name], spiral, []), length(erlang:processes())}.
{ok,79}
4> {exometer:re_register([name], spiral, []), length(erlang:processes())}.
{ok,80}
5> {exometer:re_register([name], spiral, []), length(erlang:processes())}.
{ok,81}
```
I thought that re_register should delete old metric after after creating new one. This causes process and memory leak on our system.

I use latest exometer_core 1.5.7 with erlang20, but it seems that this behaviour is common for all versions.

**Comment by saneery** [comment]
@uwiger 
Looks like 5th parameter in the tuple should be `false`: https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_admin.erl#L189

Because of this, a new entry is created on every call of re_register:
https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_admin.erl#L273-L289

**Comment by uwiger** [comment]
> @uwiger
> Looks like 5th parameter in the tuple should be `false`: https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_admin.erl#L189

No, that parameter is as it should be, but the implementation in `handle_call(...)` needs reviewing.
`AllowExisting = false` simply means that it shouldn't be interpreted as an error if the metric already exists. It does _not_ mean "simply go ahead and create a new one regardless", so there still seems to be a bug in there.

**Comment by saneery** [comment]
@uwiger Thanks for your job :pray:
When will a new release?

**Comment by netDalek** [comment]
@uwiger Thank you very much. It works
