### ISSUE TITLE
Should folsom and setup be included_applications?

### ISSUE THREAD

**Issue by kellymclaughlin** [Feuerlabs/exometer_core#14]
I'm hitting an issue where my release built with relx via rebar3 is crashing with the following output:

```
16:02:49.341 [error] CRASH REPORT Process <0.166.0> with 0 neighbours exited with reason: call to undefined function setup:find_env_vars(exometer_folsom_monitor) in gen_server:init_it/6 line 330
16:02:49.344 [error] Supervisor exometer_core_sup had child exometer_folsom_monitor started with exometer_folsom_monitor:start_link() at undefined exit with reason call to undefined function setup:find_env_vars(exometer_folsom_monitor) in context start_error
16:02:49.345 [error] CRASH REPORT Process <0.160.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,exometer_folsom_monitor,{undef,[{setup,find_env_vars,[exometer_folsom_monitor],[]},{exometer_folsom_monitor,find_env,0,[{file,"/home/kelly/repos/myapp/_build/default/lib/exometer_core/src/exometer_folsom_monitor.erl"},{line,88}]},{exomet\
er_folsom_monitor,init,1,[{file,"/home/kelly/repos/myapp/_build/default/lib/exometer_core/src/exometer_folsom_monitor.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,...}]}}},...} in application_master:init/4 line 133
16:02:49.345 [info] Application exometer_core exited with reason: {{shutdown,{failed_to_start_child,exometer_folsom_monitor,{undef,[{setup,find_env_vars,[exometer_folsom_monitor],[]},{exometer_folsom_monitor,find_env,0,[{file,"/home/kelly/repos/myapp/_build/default/lib/exometer_core/src/exometer_folsom_monitor.erl"},{line,88}]},{exometer_folsom_monitor,init,1\
,[{file,"/home/kelly/repos/myapp/_build/default/lib/exometer_core/src/exometer_folsom_monitor.erl"},{line,83}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,...}]}}},...}
```

It turns out that `setup` and `folsom` are not being included in the release because they are not listed in the `applications` or `included_applications` lists in the `exometer_core.app.src` and I don't list them explicitly in my release configuration for relx. Adding them to the release configuration fixes the issue, but it would be nice to only have to be aware of my direct dependencies when creating a release. I'm curious of your thoughts on that situation.

**Comment by tolbrino** [comment]
I believe `setup` should be included since it is mandatory during exometer's startup. `folsom` however might not be used if you don't `exometer_folsom` in your app. Thus, I think it should not be explicitely added to `exometer_core`'s dependencies.

**Comment by uwiger** [comment]
There is no good place in the .app file for specifying optional dependencies, or - as in the case of setup - dependencies that don't require the app to be started.

Adding `setup` to the `applications` list would work, but then introduces a hard requirement for `setup` to be started in all systems that want to use exometer. While some features of setup require it to be started, exometer doesn't use those.

The same issue arises for optional dependencies: exometer can't add them to `applications`, unless of course, I make a build hook for the .app file in exometer.

**Comment by uwiger** [comment]
Personally, I'm ok with adding `setup` to the `applications` list in exometer.

**Comment by kellymclaughlin** [comment]
Thanks for the feedback on this. I can submit a PR to add `setup` to the `applications` list today.

**Comment by kellymclaughlin** [comment]
https://github.com/Feuerlabs/exometer_core/pull/17

**Comment by cmkarlsson** [comment]
This has a (according to me) annoying side-effect in that application:start(setup) creates unnecessary directores in my release folder.

data.$(NODE-NAME)
log.$(NODE-NAME)

are created. Is it possible to avoid creating these directories?

I understand the issue in that you only want to know about direct dependencies but in this case starting the setup application has unwanted side-effect. 

Setup is only used for two functions (find_env_vars and get_env).  Is it a bad idea to move these functions inside exometer_core (for example exometer_core_util.erl) and drop the setup dependency?

Other solutions?
