### ISSUE TITLE
trigger_interval works incorrectly for not manual intervals

### ISSUE THREAD

**Issue by avasenin** [Feuerlabs/exometer_core#24]
If you trigger_interval for timed interval (non manual) then new interval is started but old interval isn't canceled. So after trigger_interval you will get actually two intervals.

Now I should transform all intervals to 'manual' intervals before trigger_interval to avoid this.

**Comment by uwiger** [comment]
The main idea was to use `trigger_interval()` on manual intervals, but if triggering timed intervals should be allowed at all, it had better work. ;-)

I'll take a look.

**Comment by tolbrino** [comment]
I'm closing this since PR #25 fixes this.
