### ISSUE TITLE
How to include reporters from exometer?

### ISSUE THREAD

**Issue by cmkarlsson** [Feuerlabs/exometer_core#30]
Since the split some of the reporters are still in exometer repository (exometer_report_graphite, exometer_report_snmp etc) I need to pull this as a dependency. The big problem I have here is that exometer repository is untagged (last tag is still full exometer) and it pulls the master repository from exometer_core.

Can we have exometer being tagged? and fix the dependency of exometer_core to a tagged release?

**Comment by uwiger** [comment]
I have tagged the latest exometer_core as 1.2, fixed the latest exometer_collectd to this version and tagged it to 1.0. I've then fixed exometer 1.2 to those versions.

Thanks for pointing that out.

**Comment by tolbrino** [comment]
@uwiger I think we need change logs for new releases. Maybe using something like https://github.com/skywinder/github-changelog-generator

**Comment by cmkarlsson** [comment]
Awsome! Thanks for the fast reply. From my point of view this can be closed.

Cheers!

**Comment by uwiger** [comment]
@tolbrino Looking at the github_changelog_generator, but immediately ran into the github rate limit. :)

Will revisit it later.
