### ISSUE TITLE
setup as optional application dependency 

### ISSUE THREAD

**Issue by surik** [Feuerlabs/exometer_core#47]
What do you think about this? 
Sometime I don't want to use setup but it is required and it creates some directories which i don't use (setup home directory)

**Comment by uwiger** [comment]
exometer_core uses setup for environment variable inspection, but it would be entirely possible to give setup an option to avoid verifying the directories.

**Comment by uwiger** [comment]
https://github.com/uwiger/setup/pull/20

**Comment by tolbrino** [comment]
Closing this, since uwiger/setup#20 has been merged.
