### ISSUE TITLE
Update folsom

### ISSUE THREAD

**Issue by scohen** [Feuerlabs/exometer_core#49]
The version of folsom that this project uses is unmaintained; consider switching to 
https://github.com/folsom-project

**Comment by tolbrino** [comment]
Thanks for the heads up. Do you have a pointer to an announcement. The boundary repository doesn't state anything in respect to that.

**Comment by scohen** [comment]
I stumbled upon it in the boundary repo; all issues have the same comment. 

https://github.com/boundary/folsom/issues/101

**Comment by tolbrino** [comment]
You're right, I shouldn't have looked better. We'll just wait until the tags have been migrated.

**Comment by okeuday** [comment]
I noticed the new folsom branch breaks on rebar2 due to a dependency forcing rebar3 usage.  Might be good to clear up that problem first.

**Comment by okeuday** [comment]
I might be wrong about this and remembering some other project dependency, either way it would be good to make sure the rebar support is clear.

**Comment by tolbrino** [comment]
@okeuday Could you elaborate on this, or even better provide a test case? I tried various combinations of rebar, exometer_core and folsom and couldn't find an issue.

**Comment by okeuday** [comment]
@tolbrino Sorry, I don't see this as a current issue based on my own checking.  If this was an issue with exometer repos or folsom repos, it was fixed, but I probably confused this with a different repo that was related to metrics.

**Comment by tolbrino** [comment]
@okeuday Got it. I'll keep that in mind in case we run into a similar issue.

**Comment by tolbrino** [comment]
Closing this issue, since we merged the change.
