### ISSUE TITLE
Bump lager version on next release

### ISSUE THREAD

**Issue by scohen** [Feuerlabs/exometer_core#53]
A bunch of @uwiger's projects are interdependent and rely on lager `2.0.3`, which is from early 2014.
We've been using lager `2.1.0` successfully in production with exometer for a year with no ill effects. 

FWIW, Lager is presently at version `3.0.2`.

**Comment by uwiger** [comment]
Personally, I've been using lager-3.0.1 without issues in another project.

**Comment by scohen** [comment]
So can we bump lager in `rebar.config`? Presently it's

```

**Comment by uwiger** [comment]
Is there any particular reason why you don't want to go to lager 3.0?

**Comment by uwiger** [comment]
Changing it to 3.0.2 works as far as the test suite is concerned.

**Comment by scohen** [comment]
Not at all --if you want to update it to 3.0, be my guest.

**Comment by uwiger** [comment]
Yes, I'd rather do that. Past midnight here, so I'll do it tomorrow, or merge a PR, if someone would feel like making one before then. ;-)

**Comment by tolbrino** [comment]
Merged. Although I'm late to the discussion, I've used lager 3.x recently as well and think the upgrade makes sense :-)

**Comment by scohen** [comment]
Awesome, thanks you two.
