### ISSUE TITLE
Publish Hex Package

### ISSUE THREAD

**Issue by mmmries** [Feuerlabs/exometer_core#69]
Hi. I'm working on shopgun/turtle#8 trying to make it available as a hex package. `exometer_core` is a dependency of that project and so I would also like to make this project available as a hex package.

Is this something that the maintainers of this project are interested in?
You could publish it by adding a `mix.exs` file or by using the [rebar3 plugin](https://hex.pm/docs/rebar3_usage) for hex publishing. I'd be happy to help out with a PR for either one of those solutions if you are interested. Thanks for all your work making great open source tools :heart: :heart_eyes: :tada:

**Comment by mmmries** [comment]
Am I understanding your projects dependencies correctly?
* `parse_trans` has [a hex package](https://hex.pm/packages/parse_trans) that we can depend on
* `meck` is only a testing dependency, does it needed to be loaded at runtime? If it needs to be loaded we can use [the hex package](https://hex.pm/packages/meck)
* `folsom` has a [hex package](https://hex.pm/packages/folsom)
* `hut` does not have a hex package, but [i opened an issue there to publish one](https://github.com/tolbrino/hut/issues/2)

**Comment by tolbrino** [comment]
@mmmries This looks right to me. `setup` is needed at runtime, so I guess we need to create a package for that too. Feel free to post a PR in the `setup` project, and I will look at it. Once `hut` and `setup` are taken care of, `exometer_core` can follow.

**Comment by tolbrino** [comment]
Update: `hut` has been published to hex.pm

**Comment by gmalkas** [comment]
Since it looks like `setup` is now available on hex, what's left to make this happen?

Should we change the dependencies in `rebar.config` to use hex packages instead of git repos?

Thanks

**Comment by gmalkas** [comment]
I've stumbled upon https://github.com/basho/exometer_core/pull/9 which looks like what would be needed to publish `exometer_core` to Hex.

@tolbrino I can prepare a similar PR if needed. Makes sense?
Thanks

**Comment by mmmries** [comment]
Are there two active forks of this library? It looks like `exometer_core` was already published to `hex.pm` by @licenser. If these two forks have diverged then we might need to use two separate names for the hex packages.

**Comment by Licenser** [comment]
I published a bunch of libraries for building projects, the idea is to cut red tape of publishing them that said the intention was handing them over to the maintainers as soon as they feel comfortable with it so I gladly ask the hex.pm team to re-assing the package to you

**Comment by gmalkas** [comment]
@Licenser nice, thanks!

@tolbrino is there anything preventing the next version of exometer_core to use hex packages in `rebar.config` and moving on with that?

Thanks.

**Comment by bradleyd** [comment]
bump

**Comment by mmmries** [comment]
Looks like the basho team already published their fork of the project to hex https://hex.pm/packages/exometer_core

**Comment by Licenser** [comment]
As stated before I uploaded the exometer package to hex, not to keep it but to give it to just to maintain it utill the project is ready to take it over :).

**Comment by mmmries** [comment]
Oh I forgot about that. Sorry for the confusion @Licenser. Thanks for getting things published so we can move other dependent projects forward ❤️

**Comment by benoitc** [comment]
bump. can a new release been done (not containing lager) and published to hex????

**Comment by okeuday** [comment]
Also, it would help if `setup` was in a useable state where it doesn't call remote nodes and do odd things, in the version used for the hex package.

**Comment by uwiger** [comment]
The version of setup now in hex (1.8.0) doesn't call remote nodes, and can be told not to verify directories (by setting `{verify_directories, false}`). The default is `true` for the sake of backward compatibility.

**Comment by chemeris** [comment]
Any updates on the plan for a new release and an updated hex package?

**Comment by AndrewDryga** [comment]
+1

**Comment by benoitc** [comment]
yeah would be great to have an "official" source package on hex.pm

**Comment by lpil** [comment]
Hello everyone! Would be great to have this lib on hex.pm :)

**Comment by tolbrino** [comment]
Closing this since the package on hex is up-to-date.
