### ISSUE TITLE
Is there anyway to receive multiple datapoints in a exometer_report call?

### ISSUE THREAD

**Issue by tony612** [Feuerlabs/exometer_core#77]
I'm writing a report plugin, but I need to send a whole probe(exometer_histogram) like `[{n, 9}, {min, 258}, {max, 109587} ...]`, but I found my function `exometer_report` will get the datapoints one by one. Is there anyway to implement this(like getting all points of a metric once)?

**Comment by uwiger** [comment]
As far as I could tell, it wasn't possible, but see the referenced PR.
If you add `{report_bulk, true}` when adding the reporter, then export a callback `exometer_report_bulk/3`, it will be called with `(Found, Extra, State)`, where `Found :: [{Metric, [{DataPoint, Value}]}]`

**Comment by chemeris** [comment]
Is it possible to merge this to master? We're looking for the same functionality for use with influxdb reporter.

**Comment by uwiger** [comment]
I guess sufficient time has passed for comments, so ... yes, merged.

**Comment by chemeris** [comment]
Thank you!

**Comment by tony612** [comment]
👍

**Comment by chemeris** [comment]
@uwiger I've just noticed that while batching works for predefined metrics (like a common `[erlang, memory]`), it doesn't work for runtime registered ones. E.g. I have a `spiral` and it's data points (`one` and `total`) are reported through `exometer_report_bulk/3`, but they are reported separately.

For the full picture - I'm using Elixometer to generate metrics. But I guess this shouldn't affect reporters.

Any ideas how to fix that?

**Comment by uwiger** [comment]
I guess it has to do with the intervals triggering at different points in time.

You might consider using named intervals. See the `intervals` option for configuring reporters.

**Comment by chemeris** [comment]
@uwiger I've switched to named intervals, but it didn't help.

Here you can see a predefined function metric which is processed as a single item and a spiral metric which is split into data points.
```
14:33:57.339 [info]  exometer_report_lager erlang.memory: atom=561785 binary=118416 ets=1195608 processes=12248944 total=36840312
14:33:57.339 [info]  exometer_report_lager app.spirals.sms.deliver: count=0
14:33:57.339 [info]  exometer_report_lager app.spirals.sms.deliver: one=0
```

Btw, named intervals are not mentioned anywhere in the main README, so I didn't even know they exist.

**Comment by chemeris** [comment]
@uwiger It seems this is related only to Elixometer. When reporting directly to Exometer, bulk reporting works as expected.
Sorry for a wrong alarm.
