### ISSUE TITLE
exometer_report_lager is missing

### ISSUE THREAD

**Issue by chemeris** [Feuerlabs/exometer_core#82]
Commit 83df877ba5df6541f2abdc122509e8e19020bb3a promises that removal of `exometer_report_lager` will be followed by a move of it to a separate repository. But I can't find any repo with it, so I assume it got lost. Would be really great to have it back as a separate repository.

**Comment by chemeris** [comment]
FWIW - https://github.com/fairwaves/exometer_lager

**Comment by tolbrino** [comment]
Good catch. I guess it would be nice to have a wiki page to list the known reporters. @uwiger Do you agree?

**Comment by uwiger** [comment]
FWIW, I agree (belatedly).
