### ISSUE TITLE
exometer_report:handle_call({subscribe,...}) may trigger badarg in sending

### ISSUE THREAD

**Issue by eriksoe** [Feuerlabs/exometer_core#90]
The symptom:

    =ERROR REPORT====
    ** Generic server exometer_report terminating 
    ** Last message in was {subscribe,{key,exometer_report_lager,{find,[fuse,offline_detector_buddy_fuse]},[one],true,[]},30000}
    ** When Server state == {st,[],[]}
    ** Reason for termination == 
    ** {badarg,[{exometer_report,handle_call,3,[{file,"src/exometer_report.erl"},{line,795}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

(file numbers from commit d7c4ddd).

What presumably happens:
- A reporter (here exometer_report_lager) terminates
- Its DOWN message has not been processed yet
- A send-by-registered-name it attempted while no proces is registered:
                            Reporter ! {exometer_subscribe, Metric,
                                        DataPoint, Interval, Extra};

Possible fixes - I don't know which is better:
A:
<pre>
    --- a/src/exometer_report.erl
    +++ b/src/exometer_report.erl
    @@ -792,8 +792,8 @@ handle_call({subscribe,
                 case is_valid_metric(Metric, DataPoint) of
                     true ->
                         if Status =:= enabled ->
    -                            Reporter ! {exometer_subscribe, Metric,
    -                                        DataPoint, Interval, Extra};
    +                            try_send(Reporter ! {exometer_subscribe, Metric,
    +                                                 DataPoint, Interval, Extra});
                            true -> ignore
                         end,
                         subscribe_(Reporter, Metric, DataPoint,
</pre>

B:
<pre>
    --- a/src/exometer_report.erl
    +++ b/src/exometer_report.erl
    @@ -788,12 +788,12 @@ handle_call({subscribe,
     
         %% Verify that the given metric/data point actually exist.
         case ets:lookup(?EXOMETER_REPORTERS, Reporter) of
    -        [#reporter{status = Status}] ->
    +        [#reporter{status = Status, pid=ReporterPid}] ->
                 case is_valid_metric(Metric, DataPoint) of
                     true ->
                         if Status =:= enabled ->
    -                            Reporter ! {exometer_subscribe, Metric,
    -                                        DataPoint, Interval, Extra};
    +                            ReporterPid ! {exometer_subscribe, Metric,
    +                                           DataPoint, Interval, Extra};
                            true -> ignore
                         end,
                         subscribe_(Reporter, Metric, DataPoint,
</pre>

**Comment by uwiger** [comment]
Closing this issue. Pls create a new issue if there is anything.
